### PR TITLE
Fix Windows install

### PR DESCRIPTION
**Pull request by uilianries**
fixes https://github.com/conan-community/community/issues/268

OpenCV has an evil prefix which causes Windows sabotage during install process.

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries please fix appveyor errors

**Comment by uilianries** [comment]
Okay, I gonna check it again. Seems like this change as a side-effect. I didn't see this problem when building here, probably it only occurs for a specific profile.

**Comment by mshabunin** [comment]
I'd recommend tuning installation layout with cmake options, see https://github.com/conda-forge/opencv-feedstock/pull/171 for example.

Some of options are:
* OPENCV_CONFIG_INSTALL_PATH - where cmake scripts will be installed
* OPENCV_BIN_INSTALL_PATH - where apps will be installed (dll on Windows)
* OPENCV_LIB_INSTALL_PATH - where libraries will be installed (lib on Windows)

In PR https://github.com/opencv/opencv/pull/14786 (WIP) I tried to extract all options affecting OpenCV installation layout to single file in cleaner form.

**Comment by uilianries** [comment]
Thanks @mshabunin ! I'll copy your solution!

**Comment by uilianries** [comment]
@mshabunin It worked like a charm on my machine! Thanks for helping us!

**Comment by mshabunin** [comment]
Shouldn't `package_info` method be changed too?

**Comment by SSE4** [comment]
@uilianries now it doesn't find ade.lib

**Comment by mshabunin** [comment]
> @uilianries now it doesn't find ade.lib

Looks like you need to set `OPENCV_3P_LIB_INSTALL_PATH` to `lib` too.

**Comment by mshabunin** [comment]
BTW, there is `OPENCV_LICENSES_INSTALL_PATH` parameter controlling the location of licenses installation. On Unix it defaults to `share/licenses/opencv4`, on Windows - `etc/licenses`.

Current approach with copying will not work on Linux and OSX, because licenses location is based on `CMAKE_INSTALL_DATAROOTDIR` (returned by `GnuInstallDirs` cmake module), not on `OPENCV_OTHER_INSTALL_PATH` like on Windows. For example, current Travis build on OSX prints:
```
-- Installing: /Users/travis/.conan/data/opencv/4.1.1/conan/stable/package/f8f51ec4602d95d150b128046e9a13ae33c3cf27/share/licenses/opencv4/SoftFloat-COPYING.txt
```

**Comment by uilianries** [comment]
Finally working :sweat_smile:

**Pull request merged**
