### PR TITLE
Cumulitive build fixes

### PR DESCRIPTION
**Pull request by SSE4**
closes: https://github.com/conan-community/community/issues/331 https://github.com/conan-community/community/issues/321 https://github.com/conan-community/community/issues/329 #49 #44 #47 #46 #42
supersedes: #49 #44 #47 #46 #42

contains selected (cherry-picked) changes from #49, #44, #47, #46

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
@SSE4  the MSVC 17 build failed again with protobuf. I don't see the Protobuf_BUILD_STATIC_LIBS switch beeing used. Did you rule that out locally?

**Comment by SSE4** [comment]
@martin-schulze-vireso build passed locally for me. unfortunately, `Protobuf_USE_STATIC_LIBS` didn't help for me - I still had linking errors

**Comment by martin-schulze-vireso** [comment]
@SSE4 That is strange. I erronously reported `Protobuf_BUILD_STATIC_LIBS` but it should be `Protobuf_USE_STATIC_LIBS` as you wrote above. With the latter, the builds over on my PR #46 have gone through.

**Comment by SSE4** [comment]
@martin-schulze-vireso seems like I've cherry-picked wrong commit yesterday and didn't notice the typo 🤦 
```
+        if self.options.protobuf and self.settings.compiler == 'Visual Studio' and self.options.shared:
+            # this relies on CMake's bundled FindProtobuf.cmake
+            cmake.definitions['Protobuf_BUILD_STATIC_LIBS'] = not self.options['protobuf'].shared
```

**Comment by martin-schulze-vireso** [comment]
@SSE4 I think that one goes on me. I validated that it works locally but on remote system where I had no git. So after I saw that it works I posted here and wrote up the commit, using `BUILD` instead of `USE` throughout. After I saw my error, I force pushed and edited my posts but you probably already used the broken version.

**Pull request merged**
