### PR TITLE
android: Add armv8 and x64 builds

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**

### CODE REVIEW

**Comment by Murazaki** [comment]
```
Requirements

    eigen/3.3.7 from 'conan-center' - Downloaded

    jasper/2.0.14 from 'conan-center' - Downloaded

    jbig/20160605 from 'conan-center' - Downloaded

    libjpeg/9d from 'conan-center' - Downloaded

    libpng/1.6.37 from 'conan-center' - Downloaded

    libtiff/4.0.9 from 'conan-center' - Downloaded

    libwebp/1.0.3 from 'conan-center' - Downloaded

    opencv/4.1.1@conan/stable from local cache - Cache

    protobuf/3.5.2@bincrafters/stable from 'remote2' - Downloaded

    xz_utils/5.2.4 from 'conan-center' - Downloaded

    zlib/1.2.11 from 'conan-center' - Downloaded

Packages

    eigen/3.3.7:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

    jasper/2.0.14:b75d340d6c8097eff7682f5bc088a67e2194ffa1 - Missing

    jbig/20160605:b987d606c1cfee40098f73cd108d35c6d0f087ae - Missing

    libjpeg/9d:b987d606c1cfee40098f73cd108d35c6d0f087ae - Missing

    libpng/1.6.37:dc106f813c569fc3a341b934abd663c94991049e - Missing

    libtiff/4.0.9:d3e76962ed5f83012615418e4b146e7a70698d2d - Missing

    libwebp/1.0.3:fc92d30af6d7755c6b17891ca03a366044362408 - Missing

    opencv/4.1.1@conan/stable:3254b6be21c9601f389a0b1e3af644c81ece5658 - Build

    protobuf/3.5.2@bincrafters/stable:c612c2f067f5856280c2f8137bb3407e43a5f259 - Missing

    xz_utils/5.2.4:b987d606c1cfee40098f73cd108d35c6d0f087ae - Missing

    zlib/1.2.11:b987d606c1cfee40098f73cd108d35c6d0f087ae - Missing

Cross-build from 'Linux:x86_64' to 'Android:x86_64'

Installing (downloading, building) binaries...

WARN: Migration: This conan installation doesn't have settings yet

WARN: Nothing to migrate here, settings will be generated automatically

WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json

ERROR: Missing binary: jasper/2.0.14:b75d340d6c8097eff7682f5bc088a67e2194ffa1

ERROR: Missing binary: jbig/20160605:b987d606c1cfee40098f73cd108d35c6d0f087ae

ERROR: Missing binary: libjpeg/9d:b987d606c1cfee40098f73cd108d35c6d0f087ae

ERROR: Missing binary: libpng/1.6.37:dc106f813c569fc3a341b934abd663c94991049e

ERROR: Missing binary: libtiff/4.0.9:d3e76962ed5f83012615418e4b146e7a70698d2d

ERROR: Missing binary: libwebp/1.0.3:fc92d30af6d7755c6b17891ca03a366044362408

ERROR: Missing binary: protobuf/3.5.2@bincrafters/stable:c612c2f067f5856280c2f8137bb3407e43a5f259

ERROR: Missing binary: xz_utils/5.2.4:b987d606c1cfee40098f73cd108d35c6d0f087ae

ERROR: Missing binary: zlib/1.2.11:b987d606c1cfee40098f73cd108d35c6d0f087ae

jbig/20160605: WARN: Can't find a 'jbig/20160605' package for the specified settings, options and dependencies:

- Settings: arch=x86_64, build_type=Debug, compiler=clang, compiler.version=8, os=Android, os.api_level=21

- Options: fPIC=True, shared=False

- Dependencies: 

- Requirements: 

- Package ID: b987d606c1cfee40098f73cd108d35c6d0f087ae
```

I guess you would have to build those missing packages first from https://github.com/conan-io/conan-center-index

**Comment by martin-schulze-vireso** [comment]
@Murazaki 
Yes, I expected some missing packages but that was not expected. Is there even any package binary for android downloadable on conan.io/center right now?

**Comment by Murazaki** [comment]
> 
> 
> @Murazaki
> Yes, I expected some missing packages but not all of them (except the header only one). Is there even any package binary for android downloadable on conan.io/center right now?

I'm not a maintainer but you can see some packages have been compiled for it : https://github.com/conan-io/conan-center-index/search?q=armv8&unscoped_q=armv8

you should try to build the required packages and push new architectures to conan-center-index. Maybe @SSE4 will accept them for you :)

**Comment by SSE4** [comment]
right now, there is no official bintray server providing Android binaries. users are free to set up their own bintray accounts and do their own CI (travis/appveyor/circle/azp/gihub actions/etc) to build and upload missing packages they need.

**Comment by martin-schulze-vireso** [comment]
OpenCV is hugely popular on mobile devices too, so missing out on Android and iOS would be a shame. Are there plans to integrate builds for these platforms? If so, what needs to be done, seeing that the dependencies are not available in prebuilt binary form @SSE4 .

**Comment by Croydon** [comment]
opencv/4.5.0 is now in the Conan Center Index. Please re-open a new PR there if the changes are still desired

**Pull request closed without merging**
