### PR TITLE
Building OpenCV 4.2.0

### PR DESCRIPTION
**Pull request by Murazaki**

### CODE REVIEW

**Comment by Murazaki** [comment]
Sorry I can't create the branch release/4.2.0 on your side to test this.
I ran the pipelines on my side to check though : 
https://travis-ci.org/github/Murazaki/conan-opencv/builds/680169736
https://ci.appveyor.com/project/Murazaki/conan-opencv/builds/32478186

**Comment by SSE4** [comment]
seems like OpenEXR is no longer found (on Windows):
```
CMake Error at source_subfolder/cmake/OpenCVFindLibsGrfmt.cmake:225 (add_subdirectory):
  add_subdirectory given source
  "C:/.conan/44982d/1/source_subfolder/3rdparty/openexr" which is not an
  existing directory.
Call Stack (most recent call first):
  source_subfolder/CMakeLists.txt:671 (include)

```
need to investigate...

**Comment by ericLemanissier** [comment]
probably because the patch is removed https://github.com/conan-community/conan-opencv/pull/45/files#diff-2f7ab7b985660c3574fe454a28a81c22 ?

**Comment by SSE4** [comment]
@ericLemanissier this patch should be already merged to OpenCV, but need to check if it's in 4.2.0 or later

**Comment by Murazaki** [comment]
> 
> 
> probably because the patch is removed https://github.com/conan-community/conan-opencv/pull/45/files#diff-2f7ab7b985660c3574fe454a28a81c22 ?

As @SSE4 said, I checked the patches and they mostly came from commits that were merged in OpenCV 4.2.0

But you might be right in the sense that some fixes may not correspond to ours.

**Comment by Murazaki** [comment]
https://github.com/opencv/opencv/tree/4.2.0/3rdparty/openexr
folder exists in source... might be a bug at checkout ?

**Comment by Murazaki** [comment]
I'm mad
https://github.com/opencv/opencv/pull/17537

**Pull request merged**
