### PR TITLE
Fix builds

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
libtiff has some curious configurations that are missing prebuilts from the repo.

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
This should not fix the protobuf linker errors on VS2015 /MD[d]. I don't know why there is an additional failure now.

**Comment by martin-schulze-vireso** [comment]
I tried to find out why the mac builds fail when the linux builds succeed. The command lines look nearly the same:

Mac:
```
[ 78%] Linking CXX shared library ../../../lib/libopencv_imgcodecs.dylib
cd /Users/me/.conan/data/opencv/4.1.1/_/_/build/7deb23fbcce12697d5aa459fad239eaa074efba0/build_subfolder/source_subfolder/modules/imgcodecs && /usr/local/Cellar/cmake/3.17.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_imgcodecs.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -m64 -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -O3 -DNDEBUG   -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names   -m64  -Wl,-dead_strip    -compatibility_version 4.1.0 -current_version 4.1.1 -o ../../../lib/libopencv_imgcodecs.4.1.1.dylib -install_name @rpath/libopencv_imgcodecs.4.1.dylib CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/utils.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_base.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_bmp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_exr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdal.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdcm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_hdr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pam.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pfm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_png.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pxm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_sunras.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_tiff.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/bitstrm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/rgbe.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/exif.cpp.o   \
-L/Users/me/.conan/data/libtiff/4.0.9/_/_/package/e2437fae996773a64f3ef1bf3d1a754a09fa33a4/lib  -L/Users/me/.conan/data/libwebp/1.0.3/_/_/package/925627bb9faa4169b8ec3d0d66343ea8295547e5/lib  -L/Users/me/.conan/data/libpng/1.6.37/_/_/package/eb50d18a5a5d59bd0c332464a4c348ab65e353bf/lib  -L/Users/me/.conan/data/jasper/2.0.14/_/_/package/fba1abd85cdff335628d9bcf7d65013a32b2d285/lib  -L/Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib  -L/Users/me/.conan/data/protobuf/3.5.2/bincrafters/stable/package/eec6acc43f6348a597c20e5bd28d9e0590a02597/lib  -L/Users/me/.conan/data/zlib/1.2.11/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib  -L/Users/me/.conan/data/libjpeg/9c/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib  -L/Users/me/.conan/data/xz_utils/5.2.4/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib  -L/Users/me/.conan/data/jbig/20160605/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib  -L/usr/local/lib \
 ../../../lib/libopencv_imgproc.4.1.1.dylib \
/Users/me/.conan/data/zlib/1.2.11/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib/libz.a /Users/me/.conan/data/libjpeg/9c/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib/libjpeg.a /Users/me/.conan/data/libwebp/1.0.3/_/_/package/925627bb9faa4169b8ec3d0d66343ea8295547e5/lib/libwebp.a /Users/me/.conan/data/libpng/1.6.37/_/_/package/eb50d18a5a5d59bd0c332464a4c348ab65e353bf/lib/libpng.a /Users/me/.conan/data/zlib/1.2.11/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib/libz.a /Users/me/.conan/data/libtiff/4.0.9/_/_/package/e2437fae996773a64f3ef1bf3d1a754a09fa33a4/lib/libtiff.a /Users/me/.conan/data/jasper/2.0.14/_/_/package/fba1abd85cdff335628d9bcf7d65013a32b2d285/lib/libjasper.a /Users/me/.conan/data/libjpeg/9c/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib/libjpeg.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libImath-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIlmImf-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIex-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libHalf-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIlmThread-2_3_s.a ../../../lib/libopencv_core.4.1.1.dylib /Users/me/.conan/data/zlib/1.2.11/_/_/package/f74366f76f700cc6e991285892ad7a23c30e6d47/lib/libz.a /Users/me/.conan/data/libwebp/1.0.3/_/_/package/925627bb9faa4169b8ec3d0d66343ea8295547e5/lib/libwebp.a /Users/me/.conan/data/libpng/1.6.37/_/_/package/eb50d18a5a5d59bd0c332464a4c348ab65e353bf/lib/libpng.a /Users/me/.conan/data/libtiff/4.0.9/_/_/package/e2437fae996773a64f3ef1bf3d1a754a09fa33a4/lib/libtiff.a /Users/me/.conan/data/jasper/2.0.14/_/_/package/fba1abd85cdff335628d9bcf7d65013a32b2d285/lib/libjasper.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libImath-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIlmImf-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIex-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libHalf-2_3_s.a /Users/me/.conan/data/openexr/2.3.0/_/_/package/fcd569cff780a6069f73beec399564f140e2ec33/lib/libIlmThread-2_3_s.a 
Undefined symbols for architecture x86_64:
  "_lzma_memusage", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.c.o)
  "_jbg_enc_out", referenced from:
      _JBIGEncode in libtiff.a(tif_jbig.c.o)
  "_jbg_enc_free", referenced from:
      _JBIGEncode in libtiff.a(tif_jbig.c.o)
  "_lzma_stream_decoder", referenced from:
      _LZMAPreDecode in libtiff.a(tif_lzma.c.o)
      _LZMADecode in libtiff.a(tif_lzma.c.o)
  "_lzma_lzma_preset", referenced from:
      _TIFFInitLZMA in libtiff.a(tif_lzma.c.o)
      _LZMAVSetField in libtiff.a(tif_lzma.c.o)
  "_jbg_dec_init", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_jbg_strerror", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_jbg_enc_init", referenced from:
      _JBIGEncode in libtiff.a(tif_jbig.c.o)
  "_jbg_newlen", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_jbg_dec_in", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_lzma_code", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.c.o)
      _LZMAPostEncode in libtiff.a(tif_lzma.c.o)
      _LZMAEncode in libtiff.a(tif_lzma.c.o)
  "_lzma_end", referenced from:
      _LZMASetupDecode in libtiff.a(tif_lzma.c.o)
      _LZMASetupEncode in libtiff.a(tif_lzma.c.o)
      _LZMACleanup in libtiff.a(tif_lzma.c.o)
  "_lzma_stream_encoder", referenced from:
      _LZMAVSetField in libtiff.a(tif_lzma.c.o)
      _LZMAPreEncode in libtiff.a(tif_lzma.c.o)
  "_jbg_dec_getimage", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_jbg_dec_getsize", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
  "_jbg_dec_free", referenced from:
      _JBIGDecode in libtiff.a(tif_jbig.c.o)
ld: symbol(s) not found for architecture x86_64
```
Linux:
```
[ 78%] Linking CXX shared library ../../../lib/libopencv_imgcodecs.so
cd /home/me/.conan/data/opencv/4.1.1/_/_/build/d775d5b83c0d86c9d1f2334c8f1180c1252043c7/build_subfolder/source_subfolder/modules/imgcodecs && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_imgcodecs.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC   -m64   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -O3 -DNDEBUG   -DNDEBUG   -m64  -Wl,--gc-sections    -shared -Wl,-soname,libopencv_imgcodecs.so.4.1 -o ../../../lib/libopencv_imgcodecs.so.4.1.1 CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/utils.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_base.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_bmp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_exr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdal.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_gdcm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_hdr.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_jpeg2000.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pam.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pfm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_png.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_pxm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_sunras.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_tiff.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/grfmt_webp.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/bitstrm.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/rgbe.cpp.o CMakeFiles/opencv_imgcodecs.dir/src/exif.cpp.o   \
-L/home/me/.conan/data/libtiff/4.0.9/_/_/package/70d7b3c06720160b41d7e692cffff571ddac295e/lib  -L/home/me/.conan/data/libwebp/1.0.3/_/_/package/abc00ad0249e9242a1b4cfef4dc265e67c782e32/lib  -L/home/me/.conan/data/libpng/1.6.37/_/_/package/d8b88b49d6e7691941997f64ad700b4308d0ed8c/lib  -L/home/me/.conan/data/jasper/2.0.14/_/_/package/01f70b6cacbf2eeb91056fdd6e9629ae351a156f/lib  -L/home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib  -L/home/me/.conan/data/protobuf/3.5.2/bincrafters/stable/package/82ef5eac51c38971dea2fd342dd55ddf2ddfbbc3/lib  -L/home/me/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib  -L/home/me/.conan/data/libjpeg/9c/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib  -L/home/me/.conan/data/xz_utils/5.2.4/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib  -L/home/me/.conan/data/jbig/20160605/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib \
 -Wl,-rpath,/home/me/.conan/data/libtiff/4.0.9/_/_/package/70d7b3c06720160b41d7e692cffff571ddac295e/lib:/home/me/.conan/data/libwebp/1.0.3/_/_/package/abc00ad0249e9242a1b4cfef4dc265e67c782e32/lib:/home/me/.conan/data/libpng/1.6.37/_/_/package/d8b88b49d6e7691941997f64ad700b4308d0ed8c/lib:/home/me/.conan/data/jasper/2.0.14/_/_/package/01f70b6cacbf2eeb91056fdd6e9629ae351a156f/lib:/home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib:/home/me/.conan/data/protobuf/3.5.2/bincrafters/stable/package/82ef5eac51c38971dea2fd342dd55ddf2ddfbbc3/lib:/home/me/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/me/.conan/data/libjpeg/9c/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/me/.conan/data/xz_utils/5.2.4/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/me/.conan/data/jbig/20160605/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib:/home/me/.conan/data/opencv/4.1.1/_/_/build/d775d5b83c0d86c9d1f2334c8f1180c1252043c7/build_subfolder/lib: \
../../../lib/libopencv_imgproc.so.4.1.1 -ldl -lm -lpthread -lrt \
/home/me/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a /home/me/.conan/data/libjpeg/9c/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libjpeg.a /home/me/.conan/data/libwebp/1.0.3/_/_/package/abc00ad0249e9242a1b4cfef4dc265e67c782e32/lib/libwebp.a /home/me/.conan/data/libpng/1.6.37/_/_/package/d8b88b49d6e7691941997f64ad700b4308d0ed8c/lib/libpng.a /home/me/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a -lm /home/me/.conan/data/libtiff/4.0.9/_/_/package/70d7b3c06720160b41d7e692cffff571ddac295e/lib/libtiff.a /home/me/.conan/data/jasper/2.0.14/_/_/package/01f70b6cacbf2eeb91056fdd6e9629ae351a156f/lib/libjasper.a /home/me/.conan/data/libjpeg/9c/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libjpeg.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libImath-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIlmImf-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIex-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libHalf-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIlmThread-2_3_s.a ../../../lib/libopencv_core.so.4.1.1 -lm -lpthread -lrt /home/me/.conan/data/zlib/1.2.11/_/_/package/19729b9559f3ae196cad45cb2b97468ccb75dcd1/lib/libz.a /home/me/.conan/data/libwebp/1.0.3/_/_/package/abc00ad0249e9242a1b4cfef4dc265e67c782e32/lib/libwebp.a /home/me/.conan/data/libpng/1.6.37/_/_/package/d8b88b49d6e7691941997f64ad700b4308d0ed8c/lib/libpng.a /home/me/.conan/data/libtiff/4.0.9/_/_/package/70d7b3c06720160b41d7e692cffff571ddac295e/lib/libtiff.a /home/me/.conan/data/jasper/2.0.14/_/_/package/01f70b6cacbf2eeb91056fdd6e9629ae351a156f/lib/libjasper.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libImath-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIlmImf-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIex-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libHalf-2_3_s.a /home/me/.conan/data/openexr/2.3.0/_/_/package/e71a5ca485871dd4cf15405fe4796b1ad0982620/lib/libIlmThread-2_3_s.a 
```

So far the biggest difference that I saw, was the rpath setting. However, I don't see how this should affect the linking outcome.

What makes things even worse is that `nm` reports the jbg symbols as `U` in the `imgcodecs` library for linux. However, I was able to load a jbig tiff via this opencv so they seem to be working.

**Comment by martin-schulze-vireso** [comment]
Forcing libtiff, lzma, and jbig to shared=True when opencv:shared=True just lead to another error on Macos. I am not sure if it is intended to build opencv in this way. To avoid sinking any more time into this, I would propose to cut off jbig and lzma tiff support in shared=True builds on MacOS. If someone really needs that, they should dig further into this.

**Comment by martin-schulze-vireso** [comment]
Okay, the old failing MSVC builds the linker errors/warnings mention `declspec(dllimport)` but protobuf should be statically linked. The declspec should only be activated when PROTOBUF_USE_DLLS is set, which should not be the case here.

As a sidenode: does protobuf_MSVC_STATIC_RUNTIME have anything to do with that? The  failures only happen on MD/Mdd not un MT/MTd

In this PR the failing builds for MSCV display the same jbig/lzma problem as the MacOS builds.

**Comment by martin-schulze-vireso** [comment]
The module/dnn vcxproj has set the PROTOBUF_USE_DLLS define. I cannot find why.

**Comment by martin-schulze-vireso** [comment]
Okay, after digging even deeper I think I got now what is going on.
Protobuf has an option protobuf_BUILD_SHARED_LIBS which defaults to on when the cmake variable BUILD_SHARED_LIBS is on. The latter is set by conan for the OpenCV build.

Then OpenCV finds protobuf's cmake scripts that in turn enable protobuf_BUILD_SHARED_LIBS which enables PROTOBUF_USE_DLLS on a static library build of protobuf... 

Now the question is: How do we get protobuf to link statically?

**Comment by memsharded** [comment]
Hi @SSE4 and @uilianries could you please have a look at this PR? Maybe it is time to move OpenCV to the new conan-center-index?

@martin-schulze-vireso Thanks for contributing fixes to this recipe. Please check the new ConanCenter (https://conan.io/center/), now the way to contribute recipes to it is being centralized in https://github.com/conan-io/conan-center-index (still EAP, but there are already way more packages created with this new flow than the previous ones)

It would be great to have OpenCV updated there, lets see if possible soon.

**Comment by martin-schulze-vireso** [comment]
@memsharded My last impression was that OpenCV is not yet available there and I wanted to get the current master available again, because I have a project that depends on the android changes. I am fine with moving over there but I am no maintainer of this project.

**Comment by memsharded** [comment]
> @memsharded My last impression was that OpenCV is not yet maintained there and I wanted to get the current master available again, because I have a project that depends on the android changes. I am fine with moving over there but I am no maintainer of this project and only a beginner with conan.

Sure, this is why I would prefer to move things there. The community is now focused on the new conan-center-index and its new build service, so even this PR would get way more attention there, reviews from the community, people testing it... I am fine with merging this here first if it makes sense (I'll leave it to @SSE4 and @uilianries to decide). Also no need that you move it there, this is why I was asking them if they could help, OpenCV is an important library, and it would be good to have it built by the new conan-center-index service.

**Comment by SSE4** [comment]
1. we already have several PRs fixing the builds. the most complete seems to be #44 and #47, but I still have linker errors locally with them. probably, `Protobuf_BUILD_STATIC_LIBS` might be the right thing to do, I am going to try that.
2. unfortunately, it's not a time to move OpenCV to conan-center-index yet, we have to move all its dependencies first, and it also requires GTK which we have to decide how to use (from conan package or from system package just like X11). and either way it requires X11 which is not merged yet.

**Comment by SSE4** [comment]
it's great we have a proof that build is green now.
however, I am not going to merge this one, I'll merge #50 instead. this PR does few things which I don't think we have to merge:
- enables `--build missing`
- disables `jbig` and `lzma` support

all other fixes are already incorporated into #50

**Comment by martin-schulze-vireso** [comment]
My intention was to get green builds again. Your other PR seems on track for this so I have no problem closing this.

> * enables --build missing

The first error that I saw was library without prebuilt variant so I had to use this. I don't know why this isn't an issue anymore so I am fine with tha.

> * disables jbig and lzma

I am fully with you on that. After wasting away several hours on debugging this and having no real answer how to deal with it I opted for disabling, hoping that other people would solve this.

**Comment by martin-schulze-vireso** [comment]
@SSE4 I think I found why I added the `--build missing` part: I was coming from the android side and none of the dependencies are prebuilt for android. After this (or your PR) has landed, I wanted to setup android builds in the CI. However, they will fail without the dependencies.

**Pull request closed without merging**
