### PR TITLE
update recipe

### PR DESCRIPTION
**Pull request by SSE4**
mostly works, except Clang 3.9 which crashes, known issue:
* https://github.com/opencv/opencv/issues/8010
/cc @memsharded

### CODE REVIEW

**Comment by SSE4** [comment]
@memsharded I think now it's done - I've disabled optimization for the imgwarp.cpp in case of Clang 3.9.

**Comment by jgsogo** [comment]
Hi! I've tested this PR in my Mac and compilation works ok with this profile:

```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.1
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

Nevertheless, I cannot run the example in `test_package`:

- I get this error running from repo root:
   ```
    $ pwd
    /Users/jgsogo/dev/conan-packages/conan-opencv
    $ ./test_package/build/cd3601ac1ef07679242d04c71a1f8cb266c63e70/bin/lena 
    --(!)Error loading face cascades
  ```

- And running for package build dir, it finds the face and eyes files, but something fails loading the image:

   ```
   $ pwd
   /Users/jgsogo/dev/conan-packages/conan-opencv/test_package/build/cd3601ac1ef07679242d04c71a1f8cb266c63e70
   $ ./bin/lena 
    --(!) No captured frame -- Break!
```

**Comment by SSE4** [comment]
@jgsogo yep, I've seen this message (no captured frames) on CI, will try to debug into it tomorow

**Comment by SSE4** [comment]
all problems appear to be solved, waiting for CI, and ready to be merged

**Comment by memsharded** [comment]
Great job!!!

**Comment by memsharded** [comment]
Uhm, though we have a problem, the 2.4.13 version is upper case, I will change it.

**Pull request merged**
