### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by leezu**
https://github.com/conan-community/community/issues/331

### CODE REVIEW

**Comment by leezu** [comment]
@SSE4 please review this PR. I'd like to revive your effort at https://github.com/apache/incubator-mxnet/pull/13400 with the initial limited scope of replacing the scripts used for building 3rdparty dependencies for the static build for pypi etc. ( https://github.com/apache/incubator-mxnet/tree/382279e0d5b88b2bd05e6c00105fe1e9eb2bc600/tools/dependencies )

Unfortunately the frameworks bug here blocks that (or requires shipping a patched version of opencv conan file).

**Comment by SSE4** [comment]
hi @leezu 
does the following work correctly for you?
```
self.cpp_info.frameowkrs = ['OpenCL', 'Accelerate', 'CoreMedia', 'CoreVideo', 'CoreGraphics', 'AVFoundation', 'QuartzCore', 'Cocoa']
```

**Comment by leezu** [comment]
Thanks @SSE4. Let's see what Github Actions says: https://github.com/leezu/mxnet/runs/729886913?check_suite_focus=true

**Comment by leezu** [comment]
@SSE4 setting `self.cpp_info.frameworks = ['OpenCL', 'Accelerate', 'CoreMedia', 'CoreVideo', 'CoreGraphics', 'AVFoundation', 'QuartzCore', 'Cocoa']` works. But note that it works as well without setting the frameworks.

**Comment by SSE4** [comment]
@leezu I understand it may work without these frameworks in certain cases, but you may also receive undefined references, it depends on which OpenCV APIs are you using I guess. so it's better to leave them here for the generic case.

**Comment by leezu** [comment]
Ok, thank you for clarifying. Thus let me update this PR to set `self.cpp_info.frameworks = ['OpenCL', 'Accelerate', 'CoreMedia', 'CoreVideo', 'CoreGraphics', 'AVFoundation', 'QuartzCore', 'Cocoa']` instead of deleting everything.

Can you elaborate on the process for getting this PR merged and the updated recipe published?

**Comment by leezu** [comment]
@SSE4 could you also clarify what is the gap / plan for migrating the package to https://github.com/conan-io/conan-center-index if any?

**Comment by leezu** [comment]
Ping @SSE4

**Comment by SSE4** [comment]
@leezu the plan is to first have all dependencies of OpenCV in conan-center-index. once all they are there, we can move OpenCV itself.

**Comment by SSE4** [comment]
okay, there are some linking errors on Windows related to libtiff, they appear to be unrelated, should be good to merge

**Comment by ericLemanissier** [comment]
@SSE4 https://github.com/conan-community/conan-opencv/pull/44 is a superset of this PR, and it shows that macos has the same linker errors as windows

**Comment by SSE4** [comment]
@ericLemanissier okay, I am looking at #44 locally then, as it's much more complete. we'll close #49 as soon as #44 merged.

**Comment by leezu** [comment]
@ericLemanissier it is not a superset.. #44 PR does not fix the macOS framework handling..

**Pull request closed without merging**
