### PR TITLE
OpenCV 4.3.0

### PR DESCRIPTION
**Pull request by Murazaki**
Now that the build is fixed, let's do 4.3.0.

Please redirect to the proper branch

### CODE REVIEW

**Comment by Murazaki** [comment]
There's a bug in static libraries for Mac : https://travis-ci.org/github/Murazaki/conan-opencv/jobs/697817005

**Comment by SSE4** [comment]
seems like it needs `openjpeg` dependency (it should be already available in conan). also, probably it needs a new option.

**Comment by SSE4** [comment]
changes in OpenCV: https://github.com/opencv/opencv/commit/8d78400052c9e6b60374364163f234790251b8fb
summary:
- **OpenJPEG** support has been added (for **JPEG2000** format)
- **OpenJPEG** and **Jasper** are mutually exclusive (for **JPEG2000** format)
- **OpenJPEG** has a priority over **Jasper**
- it might be the case that system **OpenJPEG** was found on Mac (e.g. one installed via **brew**)

changes in recipe to be made:
- at https://github.com/conan-community/conan-opencv/blob/22567bb3764f73db683fb79bfe831066a128627b/conanfile.py#L25 change **jasper** option to **jpeg2000** (possible values are **jasper**, **openjpeg** and **None**, with default **openjpeg**  to reflect OpenCV defaults)
- at https://github.com/conan-community/conan-opencv/blob/22567bb3764f73db683fb79bfe831066a128627b/conanfile.py#L150, conditionally require **openjpeg/3.2.1**
- at https://github.com/conan-community/conan-opencv/blob/22567bb3764f73db683fb79bfe831066a128627b/conanfile.py#L320, populate variables like **OpenJPEG_FOUND**, **OPENJPEG_LIBRARIES** and **OPENJPEG_INCLUDE_DIRS**

**Comment by Murazaki** [comment]
Ok I tried but something seems off.
OpenCV is looking for OpenJPEG package here : https://github.com/opencv/opencv/blob/8d78400052c9e6b60374364163f234790251b8fb/cmake/OpenCVFindLibsGrfmt.cmake#L158
But I can't seem to find the module that is supposed to look for it.
Thus when trying to call OpenJPEG, `find_package` changes `OpenJPEG_FOUND` to `False`.

Maybe I should just patch it and get rid of this line ?

**Comment by SSE4** [comment]
I believe setting `cmake.definitions['OpenJPEG_FOUND'] = True` in recipe should bypass the check (like it's already done for other libraries).

**Comment by Murazaki** [comment]
Job 34th failed on your side but not on mine :
https://travis-ci.org/github/Murazaki/conan-opencv/jobs/698247211
https://travis-ci.org/github/conan-community/conan-opencv/jobs/698247297

**Comment by SSE4** [comment]
appears to be infrastructure issue, relaunched

**Pull request merged**
